name: pipeline-project

on:
  push:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "GitHub Actions Student"
          
      - name: Print Production Environment Variable
        run: echo "The current environment is:${{ vars.MY_ENVIRONMENT }}"

  Linting:
    runs-on: ubuntu-latest
    
    steps:
      # 1. משכים את הקוד מהמאגר (חובה לעשות פעם אחת בתחילת הג'וב)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. הרצת Hadolint
      - name: Hadolint-scan
        run: echo "Hadolint command"

      - name: Notify Slack (Hadolint)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Hadolint worked'

      # 3. הרצת Bandit
      - name: Bandit-scan
        run: echo "bandit command"

      - name: Notify Slack (Bandit)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'bandit worked'

      # 4. הרצת Linting/Shell
      - name: Linting-scan
        run: echo "Shell command"

      - name: Notify Slack (Linting)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Linting worked'
