name: pipeline-project

on:
  push:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "GitHub Actions Student"
          
      - name: Print Production Environment Variable
        run: echo "The current environment is:${{ vars.MY_ENVIRONMENT }}"

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


#------------------Hadolint-----------------------#
      - name: Hadolint-scan
        run: echo "Hadolint command"

      - name: Notify Slack (Hadolint)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Hadolint passed'


#------------------Flask8-----------------------#
      - name: Flask8-scan
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt

      -  run: echo "python -m flask -r ."

      - name: Notify Slack (Bandit)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'bandit passed'

        
#------------------Shellcheck-----------------------#
      - name: Check scripts with Shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          files: .
          severity: error
          format: json
          shell: bash

      - name: Notify Slack (Linting)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'passed Shellcheck scan '

  Security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#------------------Trivy-----------------------#
      -  name: Install Trivy CLI
         uses: ankurk91/install-trivy-cli-action@v2
         with:
           version: latest
           cache: true
       
      - name: Run Trivy filesystem scan
        run: trivy fs --severity HIGH,CRITICAL --exit-code 1 .


#------------------Bandit-----------------------#
      - name: Run Bandit Scan
        uses: actions/setup-python@v6
        with:
          python-python: '3.13'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . --skip B311,B104


  Build-and-push: 
    runs-on: ubuntu-latest
    needs: [Linting, Security] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#------------------Docker login-----------------------#
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#------------------Docker build & Docker push-----------------------#
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test10:latest 
      
      - name: Notify Slack (Build Success)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'build and push is done'
  
  Helm-install:
    runs-on: ubuntu-latest
    needs: [Linting, Security,Build-and-push] 
#------------------Helm-install-----------------------#
    steps:
    - name: Install Helm
      uses: azure/setup-helm@v4
